### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by PeterKnightDigital** [BitPoet/ProcessAdminRemoteServer#1]
Hi BP
Tried to installed the Remote Administration Server (0.0.5) on PW 2.7.3 and had an error

Unable to install module 'ProcessAdminRemoteServer': Method Field::attr does not exist or is not callable in this context

**Comment by BitPoet** [comment]
The error should be fixed now. I've also changed the install routine so it can continue with leftovers from a failed install.

**Comment by PeterKnightDigital** [comment]
Thanks 
All worked well.
If you get a chance, can you writeup a simple bulleted instructions for both the Admin Server and the Client too?
I seem to have worked my install into a tangle :-/

**Comment by BitPoet** [comment]
Thanks for the quick feedback!
Adding an outline of how the module works and short step-by-step instructions for the setup to the readmes is already on the roadmap for when I get home from work (as well as adding more robustness to the client's install routine too).
